CREATE TABLE Alumno (
  idAlumno NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  nombre VARCHAR2(50) NOT NULL,
  apellidoPaterno VARCHAR2(50) NOT NULL,
  apellidoMaterno VARCHAR2(50) NOT NULL,
  rfc CHAR(13 CHAR) NOT NULL,
  matricula VARCHAR2(50) NOT NULL,
  idProfesor NUMBER NOT NULL,
  estatus NUMBER(1) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_alumno PRIMARY KEY (idAlumno)
);


Create Table  Grupo(
idGrupo NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
nombre varchar2(50)NOT NULL,
numero varchar2(15)NOT NULL,
estatus NUMBER(1) DEFAULT 1 NOT NULL ,
CONSTRAINT PK_Grupo Primary KEY(idGrupo)
);


CREATE TABLE Profesor (
  idProfesor NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  nombre VARCHAR2(50) NOT NULL,
  apellidoPaterno VARCHAR2(50) NOT NULL,
  apellidoMaterno VARCHAR2(50) NOT NULL,
  telefono CHAR(10 CHAR) NOT NULL,
  domicilio VARCHAR2(50) NOT NULL,
  estatus NUMBER(1) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_Profesor PRIMARY KEY (idProfesor)
);

CREATE TABLE Tesis (
  idTesis NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  tema VARCHAR2(50) NOT NULL,
  orden NUMBER(15),
  fecha DATE NOT NULL,
  estatus NUMBER(1) DEFAULT 1 NOT NULL ,
  CONSTRAINT PK_Tesis PRIMARY KEY (idTesis)
);

CREATE TABLE ConsejoAcademico (
  idConsejoAcademico NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  numero NUMBER(13) NOT NULL,
  lugar VARCHAR2(50) NOT NULL,
  componentes VARCHAR2(30) NOT NULL,
  fechaPresenta DATE NOT NULL,
  idAlumno NUMBER(10) NOT NULL,
  estatus NUMBER(1)  DEFAULT 1 NOT NULL,
  CONSTRAINT PK_ConsejoAcademico PRIMARY KEY (idConsejoAcademico)
);

CREATE TABLE AlumnoProfesor (
  idAlumnoProfesor NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  idAlumno NUMBER(10) NOT NULL,
  idProfesor NUMBER(10) NOT NULL,
  estatus NUMBER(1) DEFAULT 1 NOT NULL ,
  CONSTRAINT PK_AlumnoProfesor PRIMARY KEY (idAlumnoProfesor)
);


CREATE TABLE ProfesorConsejoAcademico (
  idProfesorConsejoAcademico NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  idProfesor NUMBER(10) NOT NULL,
  idConsejoAcademico NUMBER(10) NOT NULL,
  estatus NUMBER(1) DEFAULT 1 NOT NULL ,
  CONSTRAINT PK_ProfesorConsejoAcademico PRIMARY KEY (idProfesorConsejoAcademico)
);

CREATE INDEX IX_Alumno ON Alumno(idAlumno);
CREATE INDEX IX_Grupo ON Grupo(idGrupo);
CREATE INDEX IX_Profesor ON Profesor(idProfesor);
CREATE INDEX IX_Tesis ON Tesis(idTesis);
CREATE INDEX IX_ConsejoAcademico ON ConsejoAcademico(idConsejoAcademico);
CREATE INDEX IX_AlumnoProfesor ON AlumnoProfesor(idAlumnoProfesor);
CREATE INDEX IX_ProfesorConsejoAcademico ON ProfesorConsejoAcademico(idProfesorConsejoAcademico);


INSERT INTO Alumno (nombre, apellidoPaterno, apellidoMaterno, rfc, matricula, idProfesor)
VALUES ('Sandra', 'Toledo', 'Alonso', 'TOAS45422223', 'I17050722', 1);

INSERT INTO Alumno (nombre, apellidoPaterno, apellidoMaterno, rfc, matricula, idProfesor)
VALUES ('Marcos', 'Toledo', 'Alonso', 'GOAS45422223', 'E16050722', 2);

-- Inserciones en la tabla Grupo (Oracle)
INSERT INTO Grupo (nombre, numero)
VALUES ('Informatica', '10');

INSERT INTO Grupo (nombre, numero)
VALUES ('Electronica', '15');

-- Inserciones en la tabla Profesor (Oracle)
INSERT INTO Profesor (nombre, apellidoPaterno, apellidoMaterno, telefono, domicilio)
VALUES ('Javier', 'Campos', 'Rivera', '8661654522', 'Progreso #123');

INSERT INTO Profesor (nombre, apellidoPaterno, apellidoMaterno, telefono, domicilio)
VALUES ('Eliza', 'Carrillo', 'Rivera', '8661455534', 'El Pueblo #1234');

-- Inserciones en la tabla Tesis (Oracle)
INSERT INTO Tesis (tema, orden, fecha)
VALUES ('Pagina web', 587, TO_DATE('2023-10-30', 'YYYY-MM-DD'));

INSERT INTO Tesis (tema, orden, fecha)
VALUES ('App movil', 789, TO_DATE('2023-09-05', 'YYYY-MM-DD'));

-- Inserciones en la tabla ConsejoAcademico (Oracle)
INSERT INTO ConsejoAcademico (numero, lugar, componentes, fechaPresenta, idAlumno)
VALUES ('1235445698745', 'Monclova', 'Comou', TO_DATE('2023-06-10', 'YYYY-MM-DD'), 1);

INSERT INTO ConsejoAcademico (numero, lugar, componentes, fechaPresenta, idAlumno)
VALUES ('13', 'Audiovisual', 'Alumnos', TO_DATE('2023-08-02', 'YYYY-MM-DD'), 2);

-- Inserciones en la tabla AlumnoProfesor (Oracle)
INSERT INTO AlumnoProfesor (idAlumno, idProfesor)
VALUES (1, 1);

INSERT INTO AlumnoProfesor (idAlumno, idProfesor)
VALUES (2, 2);

-- Inserciones en la tabla ProfesorConsejoAcademico (Oracle)
INSERT INTO ProfesorConsejoAcademico (idProfesor, idConsejoAcademico)
VALUES (1, 1);

INSERT INTO ProfesorConsejoAcademico (idProfesor, idConsejoAcademico)
VALUES (2, 2);

select * from  Alumno;
select * from AlumnoProfesor ;
select * from  Grupo;
select * from  Profesor;
select * from  ProfesorConsejoAcademico;
select * from  tesis;
select * from  ConsejoAcademico;


INSERT INTO Alumno (nombre, apellidoPaterno, apellidoMaterno, rfc, matricula, idProfesor)
VALUES ('alicia', 'vazquez', 'toledo', 'AVT18422223', 'f20050722', 1);

update Profesor  set nombre ='veronica' where idProfesor = 2;

Delete Alumno where idAlumno = 3
Delete Alumno where idAlumno = 4


